<?php /** @var $block \Alan\CustomerStatus\Block\Customer\StatusForm */ ?>
<div id="custom-form">
    <form class="form" action="<?php echo $block->getPostUrl() ?>" id="custom-form" method="post" data-hasrequired="<?= __('* Required Fields')?>">
        <fieldset class="fieldset">
            <?= $block->getBlockHtml('formkey')?>
            <legend class="legend"><span><?= __("Customer Status Form") ?></span></legend><br />
            <div class="field name">
                <label class="label" for="name"><span><?=__('Status') ?></span></label>
                <div class="control">
                    <input name="customer_status" id="name" title="<?= __('Status') ?>" class="input-text" type="text"/>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="<?= __('Save') ?>" class="action submit primary" id="custom_btn">
                    <span><?= __('Save') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
